// Inline everything into one double-clickable HTML file.
//
// The app is already dependency-free, so "building" just means folding styles.css and the
// three ES modules into index.html. Modules are concatenated rather than left as separate
// files because browsers refuse to fetch module imports over file:// (CORS applies to
// file URLs); an *inline* module script with no imports is fine there.
//
// Run: node build.js  ->  dist/beer-pong.html

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const read = (p) => readFileSync(path.join(ROOT, p), 'utf8');

const stripExports = (src) => src.replace(/^export\s+(?=(default\s+)?(function|const|let|class))/gm, '');
const stripImports = (src) => src.replace(/^import\s+[\s\S]*?from\s+['"][^'"]+['"];\s*$/gm, '');

// Order matters: meter and game logic define what ui.js calls at module scope.
const meter = stripExports(read('src/meter.js'));
const game = stripExports(read('src/beerpong.js'));
const ui = stripExports(stripImports(read('src/ui.js')));

const bundle = `// Beer Pong — single-file build. Generated by build.js; edit src/ instead.\n${meter}\n${game}\n${ui}`;

let html = read('index.html');
html = html.replace(
  '<link rel="stylesheet" href="styles.css" />',
  `<style>\n${read('styles.css')}\n</style>`
);
html = html.replace(
  '<script type="module" src="src/ui.js"></script>',
  `<script type="module">\n${bundle}\n</script>`
);

// Concatenating modules merges their top-level scopes, so two files can each define a
// private helper of the same name and produce a bundle that dies on load with a
// SyntaxError. The structural checks below would still pass, so check names explicitly.
const declared = new Map();
for (const [, kind, name] of bundle.matchAll(/^(const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/gm)) {
  if (declared.has(name)) {
    throw new Error(
      `duplicate top-level declaration "${name}" (${declared.get(name)} and ${kind}) — ` +
      'the modules would collide in the bundle; rename one'
    );
  }
  declared.set(name, kind);
}

// Fail loudly rather than shipping a file that silently lost its styles or logic.
for (const [needle, what] of [['<style>', 'inlined CSS'], ['<script type="module">\n//', 'inlined JS']]) {
  if (!html.includes(needle)) throw new Error(`build produced no ${what}`);
}
if (/src=["']src\//.test(html) || /href=["']styles\.css/.test(html)) {
  throw new Error('build left an external reference behind');
}

mkdirSync(path.join(ROOT, 'dist'), { recursive: true });
const out = path.join(ROOT, 'dist', 'beer-pong.html');
writeFileSync(out, html);
console.log(`wrote ${out} (${(html.length / 1024).toFixed(1)} KB, no external files)`);
